### ISSUE TITLE
Bold font in css

### ISSUE THREAD

**Issue by kutsokon** [tristanremy/mirage#11]
@tristanremy Hey, I do like your theme, looks really fresh, but don't you think that bold style in css  is a bit redundant?
<img width="434" alt="screen shot 2017-11-11 at 2 58 02 pm" src="https://user-images.githubusercontent.com/6324101/32689623-ef22585e-c6f0-11e7-968d-cefa6954de77.png">

**Comment by tristanremy** [comment]
Thanks for the input, it does look redundant. Changed it in v0.3.2 ;)
