### ISSUE TITLE
Some transparency to scroll handle on default & hover states.

### ISSUE THREAD

**Issue by ervasive** [tristanremy/mirage#15]
Hey there, beautiful theme.

It would be nice to have a little bit of transparency on scroll handle in active tab (buffer). Currently it's impossible to see current line, error line marks etc. as the scroll handle is on top and currently has no transparency.

Expecting to see:
![1](https://user-images.githubusercontent.com/85254/32867063-919c06ae-ca73-11e7-9520-e1a51d5f3064.png)

What I actually see:
![2](https://user-images.githubusercontent.com/85254/32867066-9c92d0ba-ca73-11e7-9a75-c9851e596df4.png)

Thank you.

**Comment by tristanremy** [comment]
Should be corrected on v0.3.7, just published it if you want to update and try :) Let me know if you have any feedback ;)

**Comment by ervasive** [comment]
Works great , thank you!
