### ISSUE TITLE
Scrollbar transparent

### ISSUE THREAD

**Issue by jbrodriguez** [tristanremy/mirage#16]
Hi,

I grabbed your latest release, hoping the following issue was resolved

![screen shot 2017-11-17 at 15 19 31](https://user-images.githubusercontent.com/1305422/32967210-c20b490c-cbaa-11e7-8b57-9b297095ac90.png)

Not sure if it's visible, but the scrollbar on the right covers scm markers (added content in this case).

Is this something you would look into ?

I'm using the high contrast version and I have to say ... it's an awesome theme !!

**Comment by tristanremy** [comment]
Yes, sorry I didn't take the time to update `pastel`and `high-contrast`versions yet. It's done in v0.3.8, released a few minutes ago ;)
